"""Add meal plan model

Revision ID: 6683db363292
Revises: 4f2a31d96697
Create Date: 2026-02-02 11:56:15.812134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6683db363292'
down_revision = '4f2a31d96697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('is_cooked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_date', 'meal_plan_items', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_meal_plan_items_id'), 'meal_plan_items', ['id'], unique=False)
    op.create_index(op.f('ix_meal_plan_items_recipe_id'), 'meal_plan_items', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_meal_plan_items_user_id'), 'meal_plan_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_plan_items_user_id'), table_name='meal_plan_items')
    op.drop_index(op.f('ix_meal_plan_items_recipe_id'), table_name='meal_plan_items')
    op.drop_index(op.f('ix_meal_plan_items_id'), table_name='meal_plan_items')
    op.drop_index('idx_user_date', table_name='meal_plan_items')
    op.drop_table('meal_plan_items')
    # ### end Alembic commands ###
