"""Add price comparison tables

Revision ID: db93ba39b806
Revises: 6683db363292
Create Date: 2026-02-03 09:47:03.200875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db93ba39b806'
down_revision = '6683db363292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supermarkets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supermarkets_id'), 'supermarkets', ['id'], unique=False)
    op.create_index(op.f('ix_supermarkets_name'), 'supermarkets', ['name'], unique=True)
    op.create_table('ingredient_exclusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('supermarket_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supermarket_id'], ['supermarkets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ingredient_id', 'supermarket_id', name='uix_user_ingredient_supermarket')
    )
    op.create_index(op.f('ix_ingredient_exclusions_id'), 'ingredient_exclusions', ['id'], unique=False)
    op.create_index(op.f('ix_ingredient_exclusions_user_id'), 'ingredient_exclusions', ['user_id'], unique=False)
    op.create_table('ingredient_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('supermarket_id', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.Enum('KG', 'LITER', 'UNIT', name='unittype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supermarket_id'], ['supermarkets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'supermarket_id', 'user_id', name='uix_ingredient_supermarket_user')
    )
    op.create_index(op.f('ix_ingredient_prices_id'), 'ingredient_prices', ['id'], unique=False)
    op.create_index(op.f('ix_ingredient_prices_ingredient_id'), 'ingredient_prices', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_ingredient_prices_supermarket_id'), 'ingredient_prices', ['supermarket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_prices_supermarket_id'), table_name='ingredient_prices')
    op.drop_index(op.f('ix_ingredient_prices_ingredient_id'), table_name='ingredient_prices')
    op.drop_index(op.f('ix_ingredient_prices_id'), table_name='ingredient_prices')
    op.drop_table('ingredient_prices')
    op.drop_index(op.f('ix_ingredient_exclusions_user_id'), table_name='ingredient_exclusions')
    op.drop_index(op.f('ix_ingredient_exclusions_id'), table_name='ingredient_exclusions')
    op.drop_table('ingredient_exclusions')
    op.drop_index(op.f('ix_supermarkets_name'), table_name='supermarkets')
    op.drop_index(op.f('ix_supermarkets_id'), table_name='supermarkets')
    op.drop_table('supermarkets')
    # ### end Alembic commands ###
